# Generated by Django 4.2.1 on 2023-07-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vista", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="producto/%Y/%m/%d"
            ),
        ),
    ]
