# Generated by Django 4.2.1 on 2023-07-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vista", "0003_categoria_producto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Borrador", "Borrador"),
                    ("Publicado", "Publicado"),
                    ("Retirado", "Retirado"),
                ],
                default="Borrador",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="producto",
            name="categoria",
        ),
        migrations.AlterField(
            model_name="producto",
            name="fecha_publicacion",
            field=models.DateTimeField(verbose_name="fecha de publicacion"),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vista.categoria",
            ),
        ),
    ]
