# Generated by Django 4.2.1 on 2023-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servicio",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Estudio", "Estudio"),
                            ("Anteproyecto", "Anteproyecto"),
                            ("Proyecto", "Proyecto"),
                            ("Construccion", "Construccion"),
                            ("Finalizado", "Finalizado"),
                            ("Entregado", "Entregado"),
                            ("Pendiente", "Pendiente"),
                        ],
                        default="Estudio",
                        max_length=30,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(verbose_name="fecha de inicio")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="servicio/%Y/%m/%d"
                    ),
                ),
                ("descripcion", models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
